# This file was generated by GoReleaser. DO NOT EDIT.
cask "atc" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "ee6eca27bf18e4145442e934a0f88d7cb198195c261e2be708b57de4f1827424"
      url "https://github.com/atcprojectio/atc/releases/download/v#{version}/atc_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "4c66a2a5c1acba6d06e6ce1109c6a37b23485b9b74b1386aca673033aa10c06c"
      url "https://github.com/atcprojectio/atc/releases/download/v#{version}/atc_#{version}_darwin_arm64.zip"
    end
  end

  name "atc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atc"

  # No zap stanza required

end
