# This file was generated by GoReleaser. DO NOT EDIT.
cask "atc" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "f7b61e7b69c16f89c88dfe6972d57c7fcd7e471eb6883e24ce498c4658f3329b"
      url "https://github.com/atcprojectio/atc/releases/download/v#{version}/atc_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "d9483602d5a61d267bcaa271be74ad51981693838ac52f6541ef688a2c36b29f"
      url "https://github.com/atcprojectio/atc/releases/download/v#{version}/atc_#{version}_darwin_arm64.zip"
    end
  end

  name "atc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atc"

  # No zap stanza required

end
