# This file was generated by GoReleaser. DO NOT EDIT.
cask "atc" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "23d4dd41a09bb052b3c60cc20b52f065f3441583106b06ec4da16b219c99415c"
      url "https://github.com/atcprojectio/atc/releases/download/v#{version}/atc_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "0838d8455344588171a36d28ed06fd64979b8f87a4db95c07d167c798550c596"
      url "https://github.com/atcprojectio/atc/releases/download/v#{version}/atc_#{version}_darwin_arm64.zip"
    end
  end

  name "atc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atc"

  # No zap stanza required

end
