# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atc < Formula
  desc ""
  homepage ""
  version "0.1.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/atcprojectio/atc/releases/download/v0.1.3/atc_0.1.3_darwin_amd64.zip"
    sha256 "2bfa884266055a69cb533d3200ee25565bda8545bf2cd31c19e7082af96d989b"

    define_method(:install) do
      bin.install "atc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/atcprojectio/atc/releases/download/v0.1.3/atc_0.1.3_darwin_arm64.zip"
    sha256 "fdcc7ce49c93d0513f0cdb6c90a162a76ef81e81010bbcab53328d8f800de54b"

    define_method(:install) do
      bin.install "atc"
    end
  end
end
